### ISSUE TITLE
Help Dialog formatting missing

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-4-web#38]
when clicking on this:  

![Image](https://user-images.githubusercontent.com/699333/217081041-2b7be443-ddf0-4e29-81bd-1169d1f540b7.png)

It should look like this:

![Image](https://user-images.githubusercontent.com/699333/217081119-0cf34663-f6f9-4eb6-b9e9-18aa9105b132.png)

Instead it looks like this in staging:  

![Image](https://user-images.githubusercontent.com/699333/217081174-f065b9ab-4728-44a7-9214-62ce8ffa770a.png)

**Comment by aarontitus** [comment]
The formatting now looks good.
UX Bug: "Help" displays onHover(), but with a delay. So I click on the help button, but nothing appears. In reality, here is what is happening:
onHover(): "Oh, I see that you want me to show you the tooltip. Hang on for about 250ms"
onClick() after about 100ms: "Oh, I was going to show you the tooltip, but you clicked, which tells me that you want to turn the tooltip off. OK. I won't show you anything."

Solution: Please just display help tooltips onClick(), instead of onHover(). Clicking again anywhere should toggle the tooltip off.
